### ISSUE TITLE
Invalid Workflow File

### ISSUE THREAD

**Issue by limitMe** [superman66/wakatime-sync#10]
fork该项目之后：
- Actions 对于 forked 项目是关闭的，这一点是不是需要在文档中提一下
- 用 action.yml 的内容自己新建一个action，提示 Invalid Workflow File 错误
- 在Github Marketplace上可以直接用这个action，也是报一样的错误

```
name: wakatime-sync
uses: superman66/wakatime-sync@v1.0.0
```
```
Invalid Workflow File
No event triggers defined in `on`
```

**Comment by superman66** [comment]
@limitMe 我看你 fork 的项目 action 已经是正常运行了。所以这个 issue 遇到的问题还存在吗？

**Comment by limitMe** [comment]
在点进actions tab确认之后，确实正确运行了。之前没有。无需新建其他action.yml

**Comment by superman66** [comment]
我已经在文档补充了需要手动开启 workflow 说明了
