### ISSUE TITLE
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by Du-peng** [superman66/wakatime-sync#2]
启动脚本报错：
`D:\code\git\wakatime-sync (master -> origin) (wakatime-sync@1.0.0)                              
λ npm run start                                                                                 
                                                                                                
> wakatime-sync@1.0.0 start D:\code\git\wakatime-sync                                           
> NODE_ENV=production pm2 start pm2.json --env production                                       
                                                                                                
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序                                                                  
或批处理文件。                                                                                         
npm ERR! code ELIFECYCLE                                                                        
npm ERR! errno 1                                                                                
npm ERR! wakatime-sync@1.0.0 start: `NODE_ENV=production pm2 start pm2.json --env production`   
npm ERR! Exit status 1                                                                          
npm ERR!                                                                                        
npm ERR! Failed at the wakatime-sync@1.0.0 start script.                                        
npm ERR! This is probably not a problem with npm. There is likely additional logging output abov
                                                                                                
npm ERR! A complete log of this run can be found in:                                            
npm ERR!     C:\Users\dp\AppData\Roaming\npm-cache\_logs\2018-12-18T01_10_39_957Z-debug.log     `

**Comment by superman66** [comment]
先安装个 `cross-env`，
```
npm install cross-env -d
```
然后在命令前添加 `cross-env`
```
cross-env NODE_ENV=development babel-node src/server/index.js
```

**Comment by fangge** [comment]
按照这个方法依然会提示同样的错误

**Comment by fangge** [comment]
> 先安装个 `cross-env`，
> 
> ```
> npm install cross-env -d
> ```
> 
> 然后在命令前添加 `cross-env`
> 
> ```
> cross-env NODE_ENV=development babel-node src/server/index.js
> ```

按照这个方法依然会提示同样的错误
