### ISSUE TITLE
server酱貌似用不了

### ISSUE THREAD

**Issue by bonkyzhu** [superman66/wakatime-sync#4]
那个我按照教程一步步来, gist没有问题, server酱的推送测试没问题, 但不过就是没有给我推送代码时间

**Comment by bonkyzhu** [comment]
好像是constant中的ServiceApis的api调用是固定的Sid了?(本人不懂后端, 猜测的) 如果是, 那要怎么改呢, 不是的话是什么原因呢

**Comment by superman66** [comment]
@bonkyzhu 
是个Bug诶。我把 SCUKey 写死了。你可以看最新的代码，我已经修复了。
