### ISSUE TITLE
一个发现的问题关于配置文件

### ISSUE THREAD

**Issue by bonkyzhu** [superman66/wakatime-sync#5]
最近又重新装了一次,发现无法使用, 检查log文件发现是config语法问题, 把`// config.json`去掉就好了
```
// config.json
{
  "wakatimeApiKey": "xxxxxxxxx",
  "gistToken": "xxxxxxxxx",
  "syncGistId": "xxxxxxxxx"
}
```
(顺便貌似我的Server酱还是用不了)

**Comment by superman66** [comment]
>Sever酱用不了
@bonkyzhu 能具体说下是怎么用不了吗？Server酱 Key是否配置了呢？Server酱网页端发送测试消息微信是否能正常收到？

**Comment by superman66** [comment]
@bonkyzhu 我的锅，上次修改后忘记 push 了。
https://github.com/superman66/wakatime-sync/commit/71c1bf037139eb5a160b5f1334efadfae9989a54
