### ISSUE TITLE
同步Server酱问题

### ISSUE THREAD

**Issue by fangge** [superman66/wakatime-sync#9]
填了SCU_KEY后，微信那边能正常收到推送信息，但是上传的gist会覆盖掉已经同步了的昨天的wakatime信息，类似下图
![image](https://user-images.githubusercontent.com/1671513/76770615-3308cb80-67d9-11ea-905b-39d1fab171b3.png)
所以在dashboard那边会报错

ps: https://wakatime.chenhuichao.com/ 这个地址已经挂了

**Comment by fangge** [comment]
看了一下代码，改一下dashboard就行了，utils.js那里
` const summary = data[index].data[0];`
改成
`const summary = data[index].data ? data[index].data[0] : data[index][0];`

**Comment by superman66** [comment]
https://wakatime.chenhuichao.com 已经恢复访问了。
